### ISSUE TITLE
Install muk_attachment_lobject: bad query

### ISSUE THREAD

**Issue by ghost** [muk-it/muk_base#1]
```
2018-02-15 23:16:28,733 6034 ERROR test odoo.sql_db: bad query: b'ALTER TABLE "res_config_settings" ALTER COLUMN "attachment_location" SET NOT NULL'                            │
ERROR: column "attachment_location" contains null values                                                                                                                       │
                                                                                                                                                                               │
2018-02-15 23:16:28,733 6034 WARNING test odoo.schema: Table 'res_config_settings': unable to set NOT NULL on column 'attachment_location'!                                     │
If you want to have it, you should update the records and execute manually:                                                                                                    │
ALTER TABLE "res_config_settings" ALTER COLUMN "attachment_location" SET NOT NULL                                                                                              │
Traceback (most recent call last):                                                                                                                                             │
  File "/usr/lib/python3/dist-packages/odoo/tools/sql.py", line 109, in set_not_null                                                                                           │
    cr.execute(query)                                                                                                                                                          │
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper                                                                                                   │
    return f(self, *args, **kwargs)                                                                                                                                            │
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute                                                                                                   │
    res = self._obj.execute(query, params)                                                                                                                                     │
psycopg2.IntegrityError: column "attachment_location" contains null values            
```

**Comment by keshrath** [comment]
The error is in "muk_dms_attachment" and not in muk_attachment_lobject. It will be fixed in the next update!

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/commit/a3dd82f5d578cce03cbf10a9a644a682b8d7ab07
