### ISSUE TITLE
suspend security fails, when NoSecurityUid used in domains

### ISSUE THREAD

**Issue by katyukha** [muk-it/muk_base#12]
There is the [fix](https://github.com/OCA/server-backend/pull/37) of this bug on OCA repository. Please, apply it also to your addon.

Odoo version: 11.0

Thank you.

**Comment by katyukha** [comment]
Here is attached traceback, if it helps:

```
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/opt/odoo/odoo/odoo/service/server.py", line 1006, in preload_registries
odoo_1  |     registry = Registry.new(dbname, update_module=update_module)
odoo_1  |   File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
odoo_1  |     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
odoo_1  |   File "/opt/odoo/odoo/odoo/modules/loading.py", line 380, in load_modules
odoo_1  |     loaded_modules, update_module, models_to_check)
odoo_1  |   File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
odoo_1  |     perform_checks=perform_checks, models_to_check=models_to_check
odoo_1  |   File "/opt/odoo/odoo/odoo/modules/loading.py", line 184, in load_module_graph
odoo_1  |     _load_data(cr, module_name, idref, mode, kind='demo')
odoo_1  |   File "/opt/odoo/odoo/odoo/modules/loading.py", line 95, in _load_data
odoo_1  |     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
odoo_1  |   File "/opt/odoo/odoo/odoo/tools/convert.py", line 789, in convert_file
odoo_1  |     convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
odoo_1  |   File "/opt/odoo/odoo/odoo/tools/yaml_import.py", line 854, in yaml_import
odoo_1  |     yaml_interpreter.process(yaml_string)
odoo_1  |   File "/opt/odoo/odoo/odoo/tools/yaml_import.py", line 797, in process
odoo_1  |     self._process_node(node)
odoo_1  |   File "/opt/odoo/odoo/odoo/tools/yaml_import.py", line 808, in _process_node
odoo_1  |     self.process_record(node)
odoo_1  |   File "/opt/odoo/odoo/odoo/tools/yaml_import.py", line 316, in process_record
odoo_1  |     module, record_dict, record_id, noupdate=self.isnoupdate(record), mode=self.mode)
odoo_1  |   File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1496, in _update
odoo_1  |     record = record.create(values)
odoo_1  |   File "/opt/odoo/odoo/addons/purchase/models/account_invoice.py", line 221, in create
odoo_1  |     invoice = super(AccountInvoice, self).create(vals)
odoo_1  |   File "/opt/odoo/custom_addons/account_payment_partner/models/account_invoice.py", line 84, in create
odoo_1  |     return super(AccountInvoice, self).create(vals)
odoo_1  |   File "/opt/odoo/odoo/addons/account/models/account_invoice.py", line 481, in create
odoo_1  |     invoice = super(AccountInvoice, self.with_context(mail_create_nolog=True)).create(vals)
odoo_1  |   File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 238, in create
odoo_1  |     thread = super(MailThread, self).create(values)
odoo_1  |   File "/opt/odoo/odoo/odoo/models.py", line 3371, in create
odoo_1  |     vals = self._add_missing_default_values(vals)
odoo_1  |   File "/opt/odoo/odoo/odoo/models.py", line 1602, in _add_missing_default_values
odoo_1  |     defaults = self.default_get(list(missing_defaults))
odoo_1  |   File "/opt/odoo/odoo/addons/account/models/account_invoice.py", line 504, in default_get
odoo_1  |     res = super(AccountInvoice, self).default_get(default_fields)
odoo_1  |   File "/opt/odoo/odoo/odoo/models.py", line 1079, in default_get
odoo_1  |     defaults[name] = field.default(self)
odoo_1  |   File "/opt/odoo/odoo/addons/sale/models/account_invoice.py", line 13, in _get_default_team
odoo_1  |     return self.env['crm.team']._get_default_team_id()
odoo_1  |   File "/opt/odoo/odoo/addons/sales_team/models/crm_team.py", line 31, in _get_default_team_id
odoo_1  |     ], limit=1)
odoo_1  |   File "/opt/odoo/odoo/odoo/models.py", line 1481, in search
odoo_1  |     res = self._search(args, offset=offset, limit=limit, order=order, count=count)
odoo_1  |   File "/opt/odoo/odoo/odoo/models.py", line 3795, in _search
odoo_1  |     query = self._where_calc(args)
odoo_1  |   File "/opt/odoo/odoo/odoo/models.py", line 3585, in _where_calc
odoo_1  |     e = expression.expression(domain, self)
odoo_1  |   File "/opt/odoo/odoo/odoo/osv/expression.py", line 668, in __init__
odoo_1  |     self.parse()
odoo_1  |   File "/opt/odoo/odoo/odoo/osv/expression.py", line 968, in parse
odoo_1  |     ids1 = select_from_where(cr, field.inverse_name, comodel._table, 'id', ids2, operator)
odoo_1  |   File "/opt/odoo/odoo/odoo/osv/expression.py", line 443, in select_from_where
odoo_1  |     for i in range(0, len(where_ids), cr.IN_MAX):
odoo_1  | TypeError: object of type 'NoSecurityUid' has no len()
```

This error happenned during addon installation process.

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/9129788fb721c70d2bdabe844a7ba50dd6a0d49d

**Comment by katyukha** [comment]
Thank you) Will this fix be ported to 11.0 branch?

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/4c49631c1f5afe947044757731b1196f52188004
https://github.com/muk-it/muk_base/commit/8ab178195a8ee684c6c8c78c50875dd8b6117e45

should do it?

**Comment by katyukha** [comment]
Thank you)

**Comment by katyukha** [comment]
This issue happened again :(
Why not to add tests for this bechavior?
Please, avoid global system modifications or at least cover them with a lot of tests.
