### ISSUE TITLE
[11.0] Unable to install muk_dms_acces 

### ISSUE THREAD

**Issue by gsisa** [muk-it/muk_base#14]
Traceback (most recent call last):
  File "/opt/odoo/11.0/community/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/11.0/community/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/11.0/community/odoo/addons/base/ir/ir_model.py", line 1496, in _update
    record = record.create(values)
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_utils/models/model.py", line 150, in create
    result = result._after_create(vals)
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_utils/models/model.py", line 159, in _after_create
    self._check_recomputation(vals, [])
  File "/home/odoo/11.0/addons/muk-it/muk_dms/muk_dms/models/dms_directory.py", line 517, in _check_recomputation
    super(Directory, self)._check_recomputation(vals, olds, *largs, **kwargs)
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_security/models/access_groups.py", line 309, in _check_recomputation
    self.trigger_computation(fields)
  File "/home/odoo/11.0/addons/muk-it/muk_dms/muk_dms_access/models/dms_directory.py", line 36, in trigger_computation
    super(AccessDirectory, self).trigger_computation(fields, *largs, **kwargs)
  File "/home/odoo/11.0/addons/muk-it/muk_dms/muk_dms/models/dms_directory.py", line 230, in trigger_computation
    super(Directory, self).trigger_computation(fields, refresh=True, *largs, **kwargs)
  File "/home/odoo/11.0/addons/muk-it/muk_dms/muk_dms/models/dms_model.py", line 50, in trigger_computation
    super(DMSBaseModel, self).trigger_computation(fields, *largs, **kwargs)
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_security/models/access_groups.py", line 109, in trigger_computation
    self.suspend_security()._compute_groups()
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_security/models/access_groups.py", line 283, in _compute_groups
    record.complete_groups = record.get_groups()
  File "/home/odoo/11.0/addons/muk-it/muk_dms/muk_dms_access/models/dms_directory.py", line 51, in get_groups
    groups = super(AccessDirectory, self).get_groups()
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_security/models/access_groups.py", line 122, in get_groups
    groups |= self.groups
  File "/opt/odoo/11.0/community/odoo/fields.py", line 948, in __get__
    self.determine_value(record)
  File "/opt/odoo/11.0/community/odoo/fields.py", line 1049, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/11.0/community/odoo/models.py", line 2653, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_utils/models/model.py", line 79, in read
    result = self._after_read(result)
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_security/models/access_groups.py", line 231, in _after_read
    if self.env.user.id == SUPERUSER_ID or self._eval_access_skip("read"):
  File "/opt/odoo/11.0/community/odoo/api.py", line 799, in user
    return self(user=SUPERUSER_ID)['res.users'].browse(self.uid)
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_security/models/res_users.py", line 54, in browse
    arg = super(helper.NoSecurityUid, id).__int__()
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by gsisa** [comment]
Hi, apply this change and muk_dms_acces now enable install

```
diff --git a/muk_security/models/res_users.py b/muk_security/models/res_users.py
index 694e342..694fa04 100644
--- a/muk_security/models/res_users.py
+++ b/muk_security/models/res_users.py
@@ -51,7 +51,7 @@ class AccessUser(models.Model):

     def browse(self, arg=None, *args, **kwargs):
         if isinstance(arg, helper.NoSecurityUid):
-            arg = super(helper.NoSecurityUid, id).__int__()
+            arg = super(helper.NoSecurityUid, arg).__int__()
         return super(AccessUser, self).browse(arg=arg, **kwargs)
```
But, does not apply permissions per directory.

Thanks.

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/dd77f55f046cd136d1ef75b189556327479bb4ea

**Comment by gsisa** [comment]
Hello, error to update module with this fix.

````
diff --git a/muk_security/models/res_users.py b/muk_security/models/res_users.py
index 694e342..c88485f 100644
--- a/muk_security/models/res_users.py
+++ b/muk_security/models/res_users.py
@@ -51,8 +51,8 @@ class AccessUser(models.Model):

     def browse(self, arg=None, *args, **kwargs):
         if isinstance(arg, helper.NoSecurityUid):
-            arg = super(helper.NoSecurityUid, id).__int__()
-        return super(AccessUser, self).browse(arg=arg, **kwargs)
+            arg = super(helper.NoSecurityUid, arg).__int__()^M
+        return super(AccessUser, self).browse(arg=arg, *args **kwargs)
````
Latest lines error:
````File "/home/odoo/11.0/addons/muk-it/muk_base/muk_security/models/res_users.py", line 55, in browse
    return super(AccessUser, self).browse(arg=arg, *args **kwargs)
TypeError: unsupported operand type(s) for ** or pow(): 'tuple' and 'dict'
````
