### ISSUE TITLE
[11.0][muk_security] Error: browse() got multiple values for argument 'arg'

### ISSUE THREAD

**Issue by MathAndrews** [muk-it/muk_base#15]
Hi

I just have update my odoo 11 to the last version (11.0-20190424), and I had to update the muk_security app to avoid a issue with the `_browse` function defined in `models/res_users.py` but now I have an issue with the function `browse`

> 2019-05-14 13:22:02,201 1 INFO prp_anti werkzeug: 172.25.0.1 - - [14/May/2019 13:22:02] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1319, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1491, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 397, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 172, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 830, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1270, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1263, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1211, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1217, in render
    qcontext = self._prepare_qcontext()
  File "/mnt/extra-addons/addons_custom/fso_theme/models/ir_ui_view.py", line 19, in _prepare_qcontext
    qcontext = super(View, self)._prepare_qcontext()
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 120, in _prepare_qcontext
    qcontext = super(View, self)._prepare_qcontext()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_ui_view.py", line 13, in _prepare_qcontext
    qcontext = super(IrUiView, self)._prepare_qcontext()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1230, in _prepare_qcontext
    res_company=self.env.user.company_id.sudo(),
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 948, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1049, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2653, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_users.py", line 943, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_users.py", line 320, in read
    return super(Users, self).read(fields=fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2591, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_users.py", line 285, in _read_from_database
    super(Users, self)._read_from_database(field_names, inherited_field_names)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2737, in _read_from_database
    target = self.browse([], self._prefetch)
  File "/mnt/extra-addons/addons_download/muk_security/models/res_users.py", line 55, in browse
    return super(AccessUser, self).browse(arg=arg, *args, **kwargs)
TypeError: browse() got multiple values for argument 'arg'

Best regards,
M.

**Comment by keshrath** [comment]
I can't find a call to one of our modules in the stacktrace

**Comment by MathAndrews** [comment]
Sorry, I updated my previous comment with the correct stacktrace

**Comment by gsisa** [comment]
Hi, i resolve con this patch:

````
--- a/muk_security/models/res_users.py
+++ b/muk_security/models/res_users.py
@@ -49,17 +49,17 @@ class AccessUser(models.Model):
     # Functions
     #----------------------------------------------------------

-    def browse(self, arg=None, *args, **kwargs):
+    def browse(self, arg=None, prefetch=None):^M
         if isinstance(arg, helper.NoSecurityUid):
             arg = super(helper.NoSecurityUid, arg).__int__()
-        return super(AccessUser, self).browse(arg=arg, *args, **kwargs)
+        return super(AccessUser, self).browse(arg=arg, prefetch=prefetch)^M


     @classmethod
-    def _browse(cls, ids, *args, **kwargs):
+    def _browse(cls, ids, env, prefetch=None, add_prefetch=True):^M
         def convert_security_uid(id):
             if isinstance(id, helper.NoSecurityUid):
                 return super(helper.NoSecurityUid, id).__int__()
             return id
         access_ids = [convert_security_uid(id) for id in ids]
-        return super(AccessUser, cls)._browse(access_ids, *args, **kwargs)
+        return super(AccessUser, cls)._browse(access_ids, env=env, prefetch=prefetch, add_prefetch=add_prefetch)^M
````

**Comment by keshrath** [comment]
But than it would be no longer compatible with older versions and actually it shouldn't change anything about the implementation. Thats why I use *args and **kwargs, they are more generic.

**Comment by gsisa** [comment]
the error that @MathAndrews  report continue.

Latest error lines:
````
File "/opt/odoo/11.0/community/odoo/models.py", line 2737, in _read_from_database
    target = self.browse([], self._prefetch)
  File "/home/odoo/11.0/addons/muk-it/muk_base/muk_security/models/res_users.py", line 55, in browse
    return super(AccessUser, self).browse(arg=arg, *args, **kwargs)
TypeError: browse() got multiple values for argument 'arg'
````
Debian Stretch 64 bits
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
odoo 11.0 CE
commit 85cbb070ad0223d76abff42532999d36f712f222
Author: Nans Lefebvre <len@odoo.com>
Date:   Mon May 13 09:10:54 2019 +0000

**Comment by gsisa** [comment]
Hi @keshrath , in which situation this condition is true?

https://github.com/muk-it/muk_base/blob/11.0/muk_security/models/res_users.py#L53

thanks

**Comment by keshrath** [comment]
If you use `suspend_security` like `self.suspend_security().read([])`

**Comment by gsisa** [comment]
Hello, 
````
index c34988a..6cadd98 100644
--- a/muk_security/models/res_users.py
+++ b/muk_security/models/res_users.py
@@ -48,13 +48,14 @@ class AccessUser(models.Model):
     #----------------------------------------------------------
     # Functions
     #----------------------------------------------------------
-
-    def browse(self, arg=None, *args, **kwargs):
-        if isinstance(arg, helper.NoSecurityUid):
-            arg = super(helper.NoSecurityUid, arg).__int__()
-        return super(AccessUser, self).browse(arg=arg, *args, **kwargs)
-
-
+^M
+    def browse(self, *args, **kwargs):^M
+        if len(args) and isinstance(args[0], helper.NoSecurityUid):^M
+            args = list(args)^M
+            args[0] = super(helper.NoSecurityUid, args[0]).__int__()^M
+            args = tuple(args)^M
+        return super(AccessUser, self).browse(*args, **kwargs)^M
+^M
     @classmethod
     def _browse(cls, ids, *args, **kwargs):
         def convert_security_uid(id):
````

**Comment by keshrath** [comment]
Looks good, if it solves the problem. Can you do a PR?

**Comment by gsisa** [comment]
Hello, remote: Permission to muk-it/muk_base.git denied to gsisa.

**Comment by keshrath** [comment]
ah pull request is not a push: https://help.github.com/en/articles/creating-a-pull-request

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/ce92d6160b91129cab59895dd3f856fce5869492

**Comment by MathAndrews** [comment]
Thanks
