### ISSUE TITLE
[13.0] Installation MuK Large Objects Attachment failed

### ISSUE THREAD

**Issue by cmutz** [muk-it/muk_base#27]
Hello,

When I try to install the module MuK Large Objects Attachment, I have this error :

`NameError: name 'attach' is not defined`

Another logs : 

`2019-12-04 14:09:04,753 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:04] "GET /web/image?model=res.users&field=image_128&id=2 HTTP/1.0" 304 - 21 0.099 0.039 2019-12-04 14:09:04,755 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:04] "POST /web/dataset/call_kw/res.users/systray_get_activities HTTP/1.0" 200 - 29 0.111 0.037 2019-12-04 14:09:04,769 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:04] "POST /calendar/notify HTTP/1.0" 200 - 3 0.014 0.034 2019-12-04 14:09:04,785 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:04] "POST /web/dataset/call_kw/web.environment.ribbon.backend/get_environment_ribbon HTTP/1.0" 200 - 7 0.016 0.024 2019-12-04 14:09:04,795 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:04] "POST /web/action/load HTTP/1.0" 200 - 14 0.030 0.036 2019-12-04 14:09:04,882 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:04] "POST /web/dataset/call_kw/mail.message/load_views HTTP/1.0" 200 - 30 0.023 0.023 2019-12-04 14:09:04,929 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:04] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.0" 200 - 12 0.006 0.009 2019-12-04 14:09:04,999 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:04] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.0" 200 - 8 0.006 0.008 2019-12-04 14:09:05,733 29326 INFO ? werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:05] "GET /web_tour/static/src/xml/tip.xml HTTP/1.0" 200 - - - - 2019-12-04 14:09:06,121 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:06] "GET /dashboard HTTP/1.0" 302 - 4 0.002 0.005 2019-12-04 14:09:06,136 29326 INFO ? werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:06] "GET /backend_theme_v13/static/src/img/material-background.png HTTP/1.0" 304 - - - -
2019-12-04 14:09:07,868 29326 INFO NCS_13-02-TEST-1 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:07] "GET /web HTTP/1.0" 500 - 27 0.034 0.602
2019-12-04 14:09:07,874 29326 ERROR NCS_13-02-TEST-1 werkzeug: Error on request:
Traceback (most recent call last):
File "/opt/odoo/odoo_v13/odoo-venv/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/opt/odoo/odoo_v13/odoo-venv/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/opt/odoo/odoo_v13/server/odoo/service/server.py", line 414, in app
return self.app(e, s)
File "/opt/odoo/odoo_v13/server/odoo/service/wsgi_server.py", line 142, in application
return application_unproxied(environ, start_response)
File "/opt/odoo/odoo_v13/server/odoo/service/wsgi_server.py", line 117, in application_unproxied
result = odoo.http.root(environ, start_response)
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 1281, in call
return self.dispatch(environ, start_response)
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 1251, in call
return self.app(environ, start_wrapped)
File "/opt/odoo/odoo_v13/odoo-venv/lib/python3.7/site-packages/werkzeug/wsgi.py", line 766, in call
return self.app(environ, start_response)
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 1450, in dispatch
result = ir_http._dispatch()
File "/opt/odoo/odoo_v13/server/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
return super(Http, cls)._dispatch()
File "/opt/odoo/odoo_v13/server/addons/web_editor/models/ir_http.py", line 22, in _dispatch
return super(IrHttp, cls)._dispatch()
File "/opt/odoo/odoo_v13/server/addons/utm/models/ir_http.py", line 26, in _dispatch
response = super(IrHttp, cls)._dispatch()
File "/opt/odoo/odoo_v13/server/addons/http_routing/models/ir_http.py", line 511, in _dispatch
result = super(IrHttp, cls)._dispatch()
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_http.py", line 233, in _dispatch
return cls._handle_exception(e)
File "/opt/odoo/odoo_v13/server/addons/utm/models/ir_http.py", line 31, in _handle_exception
response = super(IrHttp, cls)._handle_exception(exc)
File "/opt/odoo/odoo_v13/server/addons/http_routing/models/ir_http.py", line 602, in _handle_exception
return super(IrHttp, cls)._handle_exception(exception)
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_http.py", line 201, in _handle_exception
return request._handle_exception(exception)
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 744, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 309, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/opt/odoo/odoo_v13/server/odoo/tools/pycompat.py", line 14, in reraise
raise value
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
result = request.dispatch()
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 803, in dispatch
r = self._call_function(**self.params) File "/opt/odoo/odoo_v13/server/odoo/http.py", line 345, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo/odoo_v13/server/odoo/service/model.py", line 93, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 341, in checked_call
result.flatten()
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 1230, in flatten
self.response.append(self.render())
File "/opt/odoo/odoo_v13/server/odoo/http.py", line 1223, in render
return env["ir.ui.view"].render_template(self.template, self.qcontext)
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_ui_view.py", line 1154, in render_template
return self.browse(self.get_view_id(template)).render(values, engine)
File "/opt/odoo/odoo_v13/server/addons/web_editor/models/ir_ui_view.py", line 25, in render
return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_ui_view.py", line 1162, in render
return self.env[engine].render(self.id, qcontext)
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_qweb.py", line 58, in render
result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/qweb.py", line 260, in render
self.compile(template, options)(self, body.append, values or {})
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: name 'attach' is not defined
Traceback (most recent call last):
File "/opt/odoo/odoo_v13/server/odoo/tools/cache.py", line 85, in lookup
r = d[key]
File "/opt/odoo/odoo_v13/server/odoo/tools/func.py", line 69, in wrapper
return func(self, *args, **kwargs)
File "/opt/odoo/odoo_v13/server/odoo/tools/lru.py", line 44, in getitem
a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb._get_asset_nodes at 0x7f1dc8438c80>, 'web.assets_backend', 'fr_FR', True, False, '', False, False, False, (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
return compiled(self, append, new, options, log)
File "", line 1, in template_web_webclient_bootstrap_628
File "", line 2, in body_call_content_626
File "", line 3, in set_625
File "", line 2, in _get_asset_nodes
File "/opt/odoo/odoo_v13/server/odoo/tools/cache.py", line 90, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_qweb.py", line 299, in _get_asset_nodes
return remains + asset.to_node(css=css, js=js, debug=debug, async_load=async_load, defer_load=defer_load, lazy_load=lazy_load)
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/assetsbundle.py", line 151, in to_node
css_attachments = self.css() or []
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/assetsbundle.py", line 332, in css
self.save_attachment("css", css)
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/assetsbundle.py", line 289, in save_attachment
attachment = ira.with_user(SUPERUSER_ID).create(values)
File "", line 2, in create
File "/opt/odoo/odoo_v13/server/odoo/api.py", line 343, in _model_create_multi
return create(self, [arg])
File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_attachment.py", line 511, in create
values.update(self._get_datas_related_values(values.pop('datas'), values['mimetype']))
File "/opt/odoo/odoo_v13/muk_addons/muk_attachment_lobject/models/ir_attachment.py", line 96, in _get_datas_related_values
return super(LObjectIrAttachment, attach)._get_datas_related_values(
NameError: name 'attach' is not defined

Error to render compiling AST
NameError: name 'attach' is not defined
Template: web.webclient_bootstrap
Path: /t/t/t[1]/t[2]
Node: - - -
2019-12-04 14:09:08,629 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:08] "POST /web/action/load HTTP/1.0" 200 - 63 0.026 0.029
2019-12-04 14:09:08,757 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:08] "POST /web/dataset/call_kw/account.journal/load_views HTTP/1.0" 200 - 74 0.044 0.061
2019-12-04 14:09:09,051 29326 INFO NCS_13-02 werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:09] "POST /web/dataset/search_read HTTP/1.0" 200 - 170 0.108 0.094
2019-12-04 14:09:09,199 29326 INFO ? werkzeug: 127.0.0.1 - - [04/Dec/2019 14:09:09] "GET /web/static/lib/Chart/Chart.js HTTP/1.0" 200 - - - -`

Regards,

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/d1d15f51806553fb415d1c5fcefb9e5534f610ae
