### ISSUE TITLE
[13.0] muk_attachment_lobject Failed migration

### ISSUE THREAD

**Issue by cmutz** [muk-it/muk_base#28]
Hello,

When I set "Storage Location" on "LOBJECT" and I click on "Force Storage Migration", I have this error :

`Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo_v13/server/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo_v13/server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo_v13/server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo_v13/server/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo_v13/server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo_v13/server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo_v13/server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo_v13/server/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo_v13/server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo_v13/server/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo_v13/server/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo_v13/server/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo_v13/server/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo_v13/muk_addons/muk_utils/models/res_config_settings.py", line 56, in action_attachment_force_storage
    self.env["ir.attachment"].force_storage()
  File "/opt/odoo/odoo_v13/muk_addons/muk_utils/models/ir_attachment.py", line 80, in force_storage
    ).migrate(batch_size=100)
  File "/opt/odoo/odoo_v13/muk_addons/muk_utils/models/ir_attachment.py", line 99, in migrate
    {"datas": attachment.datas, "mimetype": attachment.mimetype}
  File "/opt/odoo/odoo_v13/server/addons/calendar/models/ir_attachment.py", line 27, in write
    return super(Attachment, self).write(vals)
  File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_attachment.py", line 480, in write
    return super(IrAttachment, self).write(vals)
  File "/opt/odoo/odoo_v13/server/odoo/models.py", line 3547, in write
    fields[0].determine_inverse(real_recs)
  File "/opt/odoo/odoo_v13/server/odoo/fields.py", line 1084, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo_v13/server/odoo/addons/base/models/ir_attachment.py", line 203, in _inverse_datas
    super(IrAttachment, attach.sudo()).write(vals)
  File "/opt/odoo/odoo_v13/server/odoo/models.py", line 3520, in write
    field.write(self, vals[fname])
  File "/opt/odoo/odoo_v13/server/odoo/fields.py", line 934, in write
    column_value = self.convert_to_column(write_value, record)
  File "/opt/odoo/odoo_v13/muk_addons/muk_fields_lobject/fields/lobject.py", line 46, in convert_to_column
    record.env.cr._cnx.lobject(oid, "rb").unlink()
TypeError: an integer is required (got type bytes)`

Regards,

Clement

**Comment by NCS-75** [comment]
Hi,
Same issue on my side...
Any update for "TypeError: an integer is required (got type bytes)`" ?
Thanks in advance for reply
Regards

**Comment by keshrath** [comment]
The new ORM cache is sometimes a little problematic. Can you try if this commit solves the problem: https://github.com/muk-it/muk_base/commit/7db28f3b3f98a15b78d56e15b1909218607a2711

**Comment by NCS-75** [comment]
Issue is fixed, now...
Thanks for your help
