### ISSUE TITLE
[13.0] psycopg2.OperationalError: ERROR:  large object does not exist

### ISSUE THREAD

**Issue by ghost** [muk-it/muk_base#38]
On a fresh install with nothing but the MUK base and web addons enabled. I set the storage to LObject and forced migration (No files needed to migrate at this point).

I uploaded my profile picture and my companies logo to the users and companies menus which appears to have worked.
When on the main settings under configure document layout the logo appears on the preview but when you press save it errors out with the following trace;

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo-ce/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-ce/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-ce/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/odoo-ce/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-ce/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-ce/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-ce/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-ce/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-ce/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-ce/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-ce/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-ce/odoo/api.py", line 385, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/home/odoo/odoo-ce/odoo/api.py", line 365, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/odoo-ce/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/odoo-ce/odoo/models.py", line 3845, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/odoo-ce/odoo/fields.py", line 1156, in determine_inverse
    self.inverse(records)
  File "/home/odoo/odoo-ce/odoo/fields.py", line 594, in _inverse_related
    target[field.name] = record_value[record]
  File "/home/odoo/odoo-ce/odoo/models.py", line 5742, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/odoo/odoo-ce/odoo/fields.py", line 1121, in __set__
    records.write({self.name: write_value})
  File "/home/odoo/odoo-ce/addons/web/models/models.py", line 406, in write
    self._update_asset_style()
  File "/home/odoo/odoo-ce/addons/web/models/models.py", line 428, in _update_asset_style
    asset_attachment.write({'datas': b64_val})
  File "/home/odoo/odoo-ce/odoo/addons/base/models/ir_attachment.py", line 491, in write
    return super(IrAttachment, self).write(vals)
  File "/home/odoo/odoo-ce/odoo/models.py", line 3639, in write
    fields[0].determine_inverse(real_recs)
  File "/home/odoo/odoo-ce/odoo/fields.py", line 1154, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/odoo-ce/odoo/addons/base/models/ir_attachment.py", line 206, in _inverse_datas
    super(IrAttachment, attach.sudo()).write(vals)
  File "/home/odoo/odoo-ce/odoo/models.py", line 3612, in write
    field.write(self, vals[fname])
  File "/home/odoo/odoo-ce/odoo/fields.py", line 996, in write
    column_value = self.convert_to_column(write_value, record)
  File "/home/odoo/muk/base/muk_fields_lobject/fields/lobject.py", line 44, in convert_to_column
    oid = record.with_context({"oid": True})[self.name]
  File "/home/odoo/odoo-ce/odoo/models.py", line 5733, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/odoo-ce/odoo/fields.py", line 1088, in __get__
    return self.convert_to_record(value, record)
  File "/home/odoo/muk/base/muk_fields_lobject/fields/lobject.py", line 64, in convert_to_record
    lobject = record.env.cr._cnx.lobject(value, "rb")
psycopg2.OperationalError: ERROR:  large object 26473 does not exist`

**Comment by ghost** [comment]
Config File:
[options]
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
# Database Settings
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
db_host = 10.8.112.4
db_port = 5432
db_user = eajglobal
db_password = MYSUPERSECUREDBPASSWORD
db_name = eajglobal
db_template = template0
admin_passwd = MYSUPERSECUREADMINPASSWORD
db_maxconn = 64
dbfilter = eajglobal
list_db = False

#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
# Logs Settings
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
logfile = /var/log/odoo/eajglobal.log
logrotate = True
log_db = False
syslog = False
log_level = warn

#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
# Service Settings
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
proxy_mode = True
addons_path = /home/odoo/odoo-ce/addons,/home/odoo/oca/server-tools,/home/odoo/oca/server-ux,/home/odoo/oca/server-brand,/home/odoo/oca/web,/home/odoo/oca/social,/home/odoo/oca/bank-statement-import,/home/odoo/muk/base,/home/odoo/muk/web,/home/odoo/addons
pidfile = False
timezone = False
xmlrpcs = False
xmlrpc = True
xmlrpc_interface = 127.0.0.1
xmlrpc_port = 8069
longpolling_port = 8072
import_partial = 
unaccent = False
translate_modules = ['all']
server_wide_modules = None

#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
# Tuning Options
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
workers = 2
max_cron_threads = 1

#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
# Testing and Demo Settings
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
test_enable = False
test_file = False
test_report_directory = False
test_commit = False
without_demo =
