### ISSUE TITLE
[11.0] Error on Database deletion

### ISSUE THREAD

**Issue by yastri** [muk-it/muk_base#7]
Hello,

I have an error when deleted test database, after I add muk-it addons module.

1. Without install module muk_dms - Database deletion error: 'muk_dms.settings'
```
2019-02-21 04:21:22,855 1005 ERROR test4 odoo.http: muk_dms.settings
Traceback (most recent call last):
  File "/opt/odoo/server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/server/odoo/service/db.py", line 453, in dispatch
    return g[exp_method_name](*params)
  File "<decorator-gen-452>", line 2, in exp_drop
  File "/opt/odoo/server/odoo/service/db.py", line 40, in if_db_mgt_enabled
    return method(self, *args, **kwargs)
  File "/opt/odoo/server/addons-custom/muk-it/muk_dms/muk_dms_file/base/service_db.py", line 64, in exp_drop
    settings = env['muk_dms.settings'].search([('save_type', '=', 'file')])
  File "/opt/odoo/server/odoo/api.py", line 761, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo/server/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'muk_dms.settings'
```

2. With module muk_dms - Database deletion error: 'complete_base_path'
```
2019-02-21 04:24:11,072 1006 ERROR test4 odoo.http: complete_base_path
Traceback (most recent call last):
  File "/opt/odoo/server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/server/odoo/service/db.py", line 453, in dispatch
    return g[exp_method_name](*params)
  File "<decorator-gen-452>", line 2, in exp_drop
  File "/opt/odoo/server/odoo/service/db.py", line 40, in if_db_mgt_enabled
    return method(self, *args, **kwargs)
  File "/opt/odoo/server/addons-custom/muk-it/muk_dms/muk_dms_file/base/service_db.py", line 65, in exp_drop
    filestore_paths = settings.mapped('complete_base_path')
  File "/opt/odoo/server/odoo/models.py", line 4517, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/opt/odoo/server/odoo/models.py", line 4501, in _mapped_func
    vals = func(self)
  File "/opt/odoo/server/odoo/models.py", line 4763, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: 'complete_base_path'
```

I've tried to patched the module with [#63](https://github.com/muk-it/muk_dms/pull/63), there's new error when access the database with muk_dms module installed.
```
2019-02-21 05:07:18,377 3171 ERROR test4 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/server/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'test4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/server/odoo/modules/loading.py", line 383, in load_modules
    registry.setup_models(cr)
  File "/opt/odoo/server/odoo/modules/registry.py", line 267, in setup_models
    models = list(env.values())
  File "/usr/lib/python3.6/_collections_abc.py", line 762, in __iter__
    yield self._mapping[key]
  File "/opt/odoo/server/odoo/api.py", line 761, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo/server/addons-custom/muk-it/muk_base/muk_security/models/res_users.py", line 57, in _browse
    for id in ids], env, prefetch=prefetch, add_prefetch=add_prefetch)
TypeError: _browse() got an unexpected keyword argument 'add_prefetch'
```

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/pull/63
